apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-of-app
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - env: prd
  template:
    metadata:
      name: 'app-of-apps-{{ .env }}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/sbouts/argocd-apps.git
        targetRevision: HEAD
        path: 'app-of-apps/{{.env}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'argocd'
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
          - CreateNamespace=true

