apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kustomize-prd
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/sbouts/argocd-apps.git
      revision: HEAD
      directories:
      - path: 'kustomize/*'
  template:
    metadata:
      name: 'kustomize-{{ index .path.segments 1 }}-prd'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/sbouts/argocd-apps.git
        targetRevision: HEAD
        path: '{{ .path.path }}/overlays/prd'
        kustomize:
          namespace: 'kustomize-{{ index .path.segments 1 }}-prd'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'kustomize-{{ index .path.segments 1 }}-prd'
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
