apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: keycloak
    repo: https://charts.bitnami.com/bitnami
    releaseName: keycloak
    valuesFile: values.yaml
    includeCRDs: true
