apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: keycloak
    repo: https://charts.bitnami.com/bitnami
    version: 22.1.2
    releaseName: keycloak
    valuesFile: ../../base/values.yaml
    includeCRDs: true
    namespace: avp-kustomize-tst
    additionalValuesFiles:
      - values.yaml

resources:
- post-hook.yaml