apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-health-check
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 120
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: healthcheck
        image: busybox
        command:
          - /bin/sh
          - -c
          - |
            until wget --spider -S "http://keycloak" 2>&1 | grep 'HTTP/1.1 200 OK'; do
              sleep 5;
              echo 'Waiting for the keycloak service...';
            done
