apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-vault-plugin
  namespace: argocd
spec:
  destination:
    namespace: avp-test
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/sbouts/argocd-apps.git
    targetRevision: HEAD
    path: argocd-vault-plugin/plain
