apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-vault-plugin-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sbouts/argocd-apps.git
    targetRevision: HEAD
    path: argocd-vault-plugin/helm
    # helm:
    #   valueFiles:
    #     - values-base.yaml
    #     - values-prd.yaml
    #   ignoreMissingValueFiles: true
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS
          value: -f values-base.yaml
  destination:
    namespace: avp-helm
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
