apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-vault-{{ .Values.env }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: aoa-helm-vault-{{ .Values.env }}
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: helm/vault
    helm:
      valueFiles:
        - values-base.yaml
        - values-{{ .Values.env }}.yaml
    ignoreMissingValueFiles: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle    
