apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-keycloak-{{ .Values.env }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: aoa-kustomize-keycloak-{{ .Values.env }}
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: kustomize/keycloak/overlays/{{ .Values.env }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
